### PR TITLE
Update javascript-styleguide.md

### PR DESCRIPTION
**Pull request by johnpuddephatt**
Made a couple of minor amends, primarily to see if we're up and running!

### CODE REVIEW

**Comment by bernardodiasc** [comment]
Nice, thanks!

I didn't reviewed all files yet, we need to make sure to keep only the up to date and good ones :)

**Comment by johnpuddephatt** [comment]
That's cool, just wanted to see that Jekyll was playing nice.

I can confirm the barrier to entry is suitably low... I made the edit and submitted the PR all through the GitHub site, couldn't really be much simpler :)

**Comment by bernardodiasc** [comment]
This feedback of yours is really welcome! So we are in the right way!

@johnpuddephatt I gave write permission for you to send updates directly to this fork. This will speed up our tasks. Also we can make use of the issues for discussions.

**Comment by johnpuddephatt** [comment]
Awesome! 

I’m going to start posting some issues to get us started. All feedback welcomed :)

**Pull request merged**
